apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tiolu/andrewblog-backend:v1.1
        ports:
          - containerPort: 5000
        envFrom:
          - secretRef:
              name: backend-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10  
          periodSeconds: 10        
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5  
          periodSeconds: 10  